source $HOME/.zsh/prompt.sh
source $HOME/.zsh/plugins.sh
source $HOME/.zsh/history.sh
source $HOME/.zsh/dev.sh
source $HOME/.zsh/aliases.sh
source $HOME/.zsh/completion.sh
source $HOME/.zsh/navigation.sh
source $HOME/.zsh/nvm.sh
source $HOME/.zsh/path.sh